---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        exclude: ^(docs/)
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^(docs/)
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^(docs/)
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^(docs/)
      - id: check-added-large-files
        args: [--maxkb=500]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: src
        additional_dependencies: [pydantic~=2.0]
  # Temporary disabled
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.27.2
  #   hooks:
  #     - id: gitleaks
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: [.]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test, docs]
  - repo: local
    hooks:
      - id: cov-clean
        name: Coverage - Clean
        language: system
        entry: coverage erase
        types: [python]
        pass_filenames: false
        always_run: true
      - id: tox-check
        name: Tests
        entry: tox
        language: system
        pass_filenames: false
        always_run: true
      - id: cov-check
        name: Coverage
        language: system
        entry: coverage report -m --fail-under=90
        types: [python]
        pass_filenames: false
        always_run: true
      - id: cov-erase
        name: Coverage - Erase
        language: system
        entry: coverage erase
        types: [python]
        pass_filenames: false
        always_run: true
