default_language_version:
  python: python3
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        files: src
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["--skip-editable"]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test, docs]
  - repo: local
    hooks:
      - id: tox-check
        name: Tests
        entry: tox
        language: system
        pass_filenames: false
        always_run: true
      - id: cov-check
        name: Coverage
        language: system
        entry: pytest -v --cov=arta --cov-fail-under=90
        types: [ python ]
        pass_filenames: false
        always_run: true
