---
name: Documentation CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  check:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package with optional dependency 'doc'
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
      - name: Run MkDocs build
        working-directory: ./docs
        run: mkdocs build
  publish:
    if: success() && startsWith(github.ref, 'refs/tags')
    name: Publish docs on GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install package with optional dependency 'doc'
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
      - name: Run MkDocs deploy
        working-directory: ./docs
        run: mkdocs gh-deploy
        