---
name: Documentation CI/CD
on:
  push:
    branches:
      - main
    tags:
      - '*'  # Later: \b[0-9]\.[0-9]+\.[0-9]+[ab]?[0-9]?\b
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install package with optional dependency 'doc'
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
      - name: Run MkDocs build
        working-directory: ./docs
        run: mkdocs build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/site/"
  publish:
    if: success() && startsWith(github.ref, 'refs/tags')
    name: Publish doc
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
